export const projects = [
  {
    id: 1,
    title: "Potato Dieases Classifier",
    des: "An AI-powered web application that detects and classifies diseases in potato leaves using image processing and deep learning. Upload a photo of a potato leaf, and the app will identify the disease and show the confidence level of the prediction.",
    img: "/farmerphotato.png",
    iconLists: ["/re.svg", "/Python.svg", "/FastAPI.svg", "/TensorFlow.svg", "/Docker.svg"],
    link: "https://github.com/RND036/Potatodisease.git",
  },
  {
    id: 2,
    title: "Hardware Store App",
    des: "Built a feature-rich Flutter shopping app with custom API auth, offline support, geolocation, QR scanning, battery tracking, and responsive UI with dark mode.",
    img: "/hardwarestore.png",
    iconLists: ["/Flutter.svg", "/Dart.svg", "/MongoDB.svg", "/MySQL.svg","/Postman.svg"],
    link: "https://github.com/RND036/HardwareStoreApp-Flutter.git",
  },
  {
    id: 3,
    title: "Hand Gesture Game Control",
    des: "Control games using hand gestures through your webcam! This Python application uses computer vision to detect hand gestures and translates them into keyboard inputs for gaming.",
    img: "/game.png",
    iconLists: ["/Python.svg", "/OpenCV.svg", "/keyboard.svg"],
    link: "https://github.com/RND036/GamePlay-CV.git",
  },
  {
    id: 4,
    title: "Pet Care management System",
    des: "Built a full-featured web platform for pet owners and vets using Laravel and Jetstream, featuring vaccination tracking, appointment booking, emergency QR access, real-time chat (via Chatify), and an integrated pet store. Implemented role-based access for admins, vets, and users, with inventory management and analytics support.",
    img: "/petcare.png",
    iconLists: ["/Laravel.svg", "/MySQL.svg", "/Livewire.svg", "/Jira.svg", "/Slack.svg"],
    link: "https://github.com/RND036/PetCare_Web.git",
  },
   {
    id: 5,
    title: "Spam Classifier",
    des: "Developed a web-based spam email classifier using Django and machine learning. Implemented NLP techniques like punctuation removal, stopword filtering, and stemming, then converted text data using CountVectorizer. Trained a RandomForestClassifier to detect spam and integrated it into a user-friendly web interface for real-time predictions.",
    img: "/emailclassifier.png",
    iconLists: ["/Python.svg", "/Django.svg", "/NumPy.svg", "/Pandas.svg", "/scikit-learn.svg"],
    link: "https://github.com/RND036/Spamclassifier.git",
  },
   {
    id: 6,
    title: "House Price Prediction",
    des: "Designed a machine learning-powered web app to estimate house prices using Linear Regression. Preprocessed data with pandas and generated visual insights using matplotlib and seaborn. Integrated user input for predictions and deployed the model using Django and joblib for real-time access.",
    img: "/houseprice.png",
    iconLists: ["/Django.svg", "/Pandas.svg", "/NumPy.svg", "/scikit-learn.svg","/seaborn.svg"],
    link: "https://github.com/RND036/Housepriceprediction.git",
  },
   {
    id: 7,
    title: "Real Time Vehicle Counting ",
    des: "YOLOv11 realtime vehicle counting system using Python and OpenCV. This project utilizes YOLOv11 for real-time object detection and counting of vehicles in video streams. It processes video input to detect and count vehicles, providing real-time analytics on traffic flow.",
    img: "/vehiclecounting.png",
    iconLists: ["/yolo.svg","/Python.svg"],
    link: "https://github.com/RND036/Realtime-Vehicle-Counting.git",
  },
   {
    id: 8,
    title: "Customer Segmentation",
    des: "This project performs customer segmentation using the K-Means clustering algorithm, an unsupervised machine learning technique. It helps businesses categorize customers based on features like age, income, and spending behavior for more personalized marketing strategies and improved customer experience.",
    img: "/customersegementation.png",
    iconLists: ["/Pandas.svg", "/NumPy.svg", "/Matplotlib.svg", "/scikit-learn.svg", "/seaborn.svg"],
    link: "https://github.com/RND036/Customersegmentation.git",
  },
    {
    id: 9,
    title: "Hardware Store Website",
    des: "Developed a robust, feature-rich website for a hardware store, offering streamlined management for admins and a user-friendly interface for customers. This project focuses on optimizing both the back-end and front-end functionalities to improve store operations.",
    img: "/hardwarestoreweb.png",
    iconLists: ["/Laravel.svg", "/Livewire.svg", "/MongoDB.svg", "/MYSQL.svg", "/tail.svg"],
    link: "https://github.com/RND036/Hardware-Store.git",
  },
    {
    id: 10,
    title: "Expense Tracker Application",
    des: "Developed an Expense Tracker application using Filament Panels to enhance financial management. This web application empowers users to effectively manage their finances ",
    img: "/expensetracker.png",
    iconLists: ["/Laravel.svg", "/PHP.svg", "/tail.svg", "/Css3.svg", "/JavaScript.svg"],
    link: "https://www.linkedin.com/in/ravishka-dissanayaka-630263281/details/projects/",
  },
    {
    id: 8,
    title: "Stock Management System",
    des: "This C# Windows Forms application leverages Object-Oriented Programming and SQL integration to deliver an efficient stock management system. Designed with a secure login for authorized administrators, it offers a user-friendly interface with features like item addition, removal, and quantity updates. The system includes a detailed stock overview and a transaction log to ensure transparency and traceability. Combining the power of C# and SQL, its a robust solution for streamlined, secure, and effective inventory management.",
    img: "/stockmanagemnt.png",
    iconLists: ["/Csharp.svg", "/MySQL.svg"],
    link: "https://github.com/RND036/Customersegmentation.git",
  },
    {
    id: 8,
    title: "Travel Website",
    des: "Developed a responsive travel website using React, featuring dynamic destination listings, interactive user interface, and seamless navigation. Integrated modern design principles to enhance user experience and provide an engaging platform for exploring travel packages and destinations",
    img: "/travel.png",
    iconLists: ["/re.svg", "/Bootstrap.svg", "/CSS3.svg"],
    link: "https://indotravitravels.netlify.app",
  },
];